import torch
from transformers import BartTokenizer, BartForConditionalGeneration, AdamW
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm

# ----------------------------------------
# 1. 数据集
# ----------------------------------------
# 数据集样本
data = [
    ("我爱中国", "I love China"),
    ("今天天气很好", "The weather is nice today"),
    ("你好吗", "How are you?"),
    ("谢谢你", "Thank you"),
    ("我喜欢看电影", "I like watching movies"),
    ("我爱美国", "I love the United States"),
    ("我爱日本", "I love Japan"),
    ("我爱法国", "I love France"),
    ("我爱德国", "I love Germany"),
    ("这是一本书", "This is a book"),
    ("他是我的朋友", "He is my friend"),
    ("她很聪明", "She is very smart"),
    ("这个城市很美丽", "This city is beautiful"),
    ("我正在学习中文", "I am learning Chinese"),
    ("你住在哪里", "Where do you live?"),
    ("我在北京", "I live in Beijing"),
    ("你今天过得怎么样", "How was your day today?"),
    ("我很累", "I am tired"),
    ("你喜欢什么颜色", "What is your favorite color?"),
    ("我喜欢蓝色", "I like blue"),
    ("你会说英语吗", "Can you speak English?"),
    ("我会说一点英语", "I can speak a little English"),
    ("你吃了吗", "Have you eaten?"),
    ("我还没吃", "I haven't eaten yet"),
    ("这道菜很好吃", "This dish is delicious"),
    ("明天我们去旅游", "We will travel tomorrow"),
    ("我爱英国", "I love the United Kingdom"),
    ("我爱加拿大", "I love Canada"),
    ("我爱澳大利亚", "I love Australia"),
    ("我爱意大利", "I love Italy"),
    ("我爱西班牙", "I love Spain"),
    ("你想去哪里", "Where do you want to go?"),
    ("我想去上海", "I want to go to Shanghai"),
    ("这本书很有意思", "This book is interesting"),
    ("他每天跑步", "He runs every day"),
    ("我们要一起努力", "We need to work hard together"),
    ("这个问题很难", "This problem is difficult"),
    ("我没有时间", "I don't have time"),
    ("你能帮我吗", "Can you help me?"),
    ("今天的天气很不错", "The weather is quite nice today"),
    ("他喜欢吃辣的食物", "He likes to eat spicy food"),
    ("我刚刚完成了工作", "I just finished my work"),
    ("她每天都去跑步", "She goes jogging every day"),
    ("我们计划下周去旅行", "We plan to travel next week"),
    ("他正在学习一门新语言", "He is learning a new language"),
    ("这本书非常有趣", "This book is very interesting"),
    ("我家附近有一个大公园", "There is a big park near my house"),
    ("她的笑容很迷人", "Her smile is charming"),
    ("我喜欢和朋友一起看电影", "I like watching movies with friends"),
    ("今天我做了一顿美味的晚餐", "I made a delicious dinner today"),
    ("他每天都早起跑步", "He wakes up early to run every day"),
    ("她有一只非常可爱的狗", "She has a very cute dog"),
    ("我们已经准备好迎接客人", "We are ready to welcome the guests"),
    ("我喜欢在周末去健身房锻炼", "I like going to the gym to work out on weekends"),
    ("他刚刚从国外回来", "He just came back from abroad"),
    ("我的父母很喜欢旅行", "My parents love to travel"),
    ("我们决定去海边度假", "We decided to go to the beach for vacation"),
    ("她的房间里有很多书籍", "There are many books in her room"),
    ("我刚买了一辆新车", "I just bought a new car"),
    ("我很高兴认识你", "Nice to meet you"),
    ("我也很高兴", "I am also very happy"),
    ("你会做饭吗", "Can you cook?"),
    ("我不会做饭", "I can't cook"),
    ("我喜欢听音乐", "I like listening to music"),
    ("你喜欢什么运动", "What sports do you like?"),
    ("我喜欢打篮球", "I like playing basketball"),
    ("你会游泳吗", "Can you swim?"),
    ("我不会游泳", "I can't swim"),
    ("今天是星期天", "Today is Sunday"),
    ("你有兄弟姐妹吗", "Do you have any siblings?"),
    ("我有一个姐姐", "I have an older sister"),
    ("我没有兄弟姐妹", "I don't have any siblings"),
    ("我正在工作", "I am working"),
    ("你在做什么", "What are you doing?"),
    ("我在看书", "I am reading a book"),
    ("他很喜欢跑步", "He really likes running"),
    ("她去上学了", "She went to school"),
    ("我们去吃晚餐", "Let's go for dinner"),
    ("我可以借你的笔吗", "Can I borrow your pen?"),
    ("这是我的手机", "This is my phone"),
    ("你喜欢喝咖啡吗", "Do you like drinking coffee?"),
    ("我不喜欢咖啡", "I don't like coffee"),
    ("这是一只猫", "This is a cat"),
    ("我想买一台电脑", "I want to buy a computer"),
    ("你去过哪里旅行", "Where have you traveled?"),
    ("我去过日本", "I have been to Japan"),
    ("我爱读小说", "I love reading novels"),
    ("我爱吃火锅", "I love eating hotpot"),
    ("我爱吃巧克力", "I love eating chocolate"),
    ("我爱爬山", "I love hiking"),
    ("我爱骑自行车", "I love cycling"),
    ("我爱看风景", "I love sightseeing"),
    ("我爱摄影", "I love photography"),
    ("我爱动物", "I love animals"),
    ("我爱大自然", "I love nature"),
    ("我爱看电视", "I love watching TV"),
    ("我爱去购物", "I love shopping"),
    ("我爱去海边", "I love going to the beach"),
    ("我爱看戏剧", "I love watching dramas"),
    ("我爱烹饪", "I love cooking"),
    ("我爱收集邮票", "I love collecting stamps"),
    ("我爱唱歌", "I love singing"),
    ("我爱写诗", "I love writing poetry"),
    ("我爱做运动", "I love doing sports"),
    ("我爱做瑜伽", "I love doing yoga"),
    ("我爱吃甜点", "I love eating desserts"),
    ("我爱吃蛋糕", "I love eating cake"),
    ("我爱唱卡拉OK", "I love singing karaoke"),
    ("我爱喝果汁", "I love drinking juice"),
    ("我爱喝红茶", "I love drinking black tea"),
    ("我爱喝啤酒", "I love drinking beer"),
    ("我爱吃炸鸡", "I love eating fried chicken"),
    ("我爱吃披萨", "I love eating pizza"),
    ("我爱吃面条", "I love eating noodles"),
    ("我爱吃汉堡", "I love eating hamburgers"),
    ("我爱吃薯条", "I love eating fries"),
    ("我爱做手指饼干", "I love making finger biscuits"),
    ("我爱喝牛奶", "I love drinking milk"),
    ("我爱喝水", "I love drinking water"),
    ("我喜欢吃苹果", "I like eating apples"),
    ("你喜欢吃什么", "What do you like to eat?"),
    ("你会唱歌吗", "Can you sing?"),
    ("我喜欢唱歌", "I like singing"),
    ("你住在哪个城市", "Which city do you live in?"),
    ("我住在上海", "I live in Shanghai"),
    ("今天我很忙", "I am very busy today"),
    ("你喜欢看什么电影", "What movies do you like to watch?"),
    ("我喜欢看科幻片", "I like watching science fiction movies"),
    ("他很喜欢看足球", "He really likes watching soccer"),
    ("你能告诉我吗", "Can you tell me?"),
    ("我不知道", "I don't know"),
    ("你几点下班", "What time do you finish work?"),
    ("我六点下班", "I finish work at 6 o'clock"),
    ("今天我有点不舒服", "I feel a little sick today"),
    ("你要喝水吗", "Do you want to drink water?"),
    ("我很渴", "I am thirsty"),
    ("今天我学到了很多新东西", "I learned a lot of new things today"),
    ("他的家乡在一个小村庄里", "His hometown is in a small village"),
    ("我已经准备好参加会议", "I am ready for the meeting"),
    ("她每天都会做瑜伽", "She practices yoga every day"),
    ("我的手机快没电了", "My phone is about to run out of battery"),
    ("我们计划明天去购物", "We plan to go shopping tomorrow"),
    ("他喜欢在晚上喝一杯咖啡", "He likes to drink a cup of coffee at night"),
    ("我对未来充满了期待", "I am full of expectations for the future"),
    ("我们一起做了一个蛋糕", "We made a cake together"),
    ("她喜欢在周末看电影", "She enjoys watching movies on weekends"),
    ("这次旅行给我留下了深刻的印象", "This trip left a deep impression on me"),
    ("我每天都看新闻了解世界动态", "I watch the news every day to stay informed about the world"),
    ("他总是准时参加会议", "He always attends meetings on time"),
    ("我们在城市中心有一个小公寓", "We have a small apartment in the city center"),
    ("我打算下个月换一份工作", "I plan to change jobs next month"),
    ("她对艺术有浓厚的兴趣", "She has a strong interest in art"),
    ("我和我的朋友们去看了演唱会", "My friends and I went to a concert"),
    ("他喜欢在周末做家务", "He likes to do housework on weekends"),
    ("我的父母非常支持我", "My parents are very supportive of me"),
    ("我今天早上喝了一杯咖啡", "I had a cup of coffee this morning"),
    ("这部电影非常感人", "This movie is very touching"),
    ("我很享受独自旅行的时光", "I really enjoy traveling alone"),
    ("她喜欢听古典音乐", "She likes to listen to classical music"),
    ("我去过很多不同的国家", "I have been to many different countries"),
    ("他正在准备一次重要的演讲", "He is preparing for an important speech"),
    ("我的家人总是在节假日团聚", "My family always reunites during holidays"),
    ("这家餐馆的食物非常好吃", "The food at this restaurant is very delicious"),
    ("我最近学会了做意大利面", "I recently learned how to make spaghetti"),
    ("他们的婚礼在春天举行", "Their wedding is held in the spring"),
    ("我喜欢在清晨散步", "I like walking in the early morning"),
    ("我正在看电视", "I am watching TV"),
    ("你喜欢动物吗", "Do you like animals?"),
    ("我喜欢狗", "I like dogs"),
    ("你喜欢猫还是狗", "Do you like cats or dogs?"),
    ("我喜欢狗", "I like dogs"),
    ("你喜欢跑步吗", "Do you like running?"),
    ("我喜欢跑步", "I like running"),
    ("他喜欢打篮球", "He likes playing basketball"),
    ("今天的课很有趣", "Today's lesson is interesting"),
    ("你会开车吗", "Can you drive?"),
    ("我会开车", "I can drive"),
    ("你喜欢什么食物", "What food do you like?"),
    ("我喜欢吃披萨", "I like eating pizza"),
    ("你喜欢什么季节", "What season do you like?"),
    ("我喜欢春天", "I like spring"),
    ("今天很热", "It's very hot today"),
    ("我觉得这部电影很有趣", "I think this movie is interesting"),
    ("你知道这个地方吗", "Do you know this place?"),
    ("我知道这个地方", "I know this place"),
    ("这辆车很贵", "This car is expensive"),
    ("你喜欢这个颜色吗", "Do you like this color?"),
    ("我喜欢红色", "I like red"),
    ("你什么时候回家", "When are you going home?"),
    ("我晚上回家", "I am going home in the evening"),
    ("你做什么工作", "What do you do for work?"),
    ("我是医生", "I am a doctor"),
    ("我很喜欢旅行", "I really like traveling"),
    ("你喜欢吃什么水果", "What fruit do you like to eat?"),
    ("我喜欢吃香蕉", "I like eating bananas"),
    ("你会弹钢琴吗", "Can you play the piano?"),
    ("我会弹钢琴", "I can play the piano"),
    ("我喜欢喝茶", "I like drinking tea"),
    ("你喜欢喝茶吗", "Do you like drinking tea?"),
    ("今天是我的生日", "Today is my birthday"),
    ("祝你生日快乐", "Happy birthday to you"),
    ("我喜欢去海边", "I like going to the beach"),
    ("你今天吃了什么", "What did you eat today?"),
    ("我吃了米饭", "I ate rice"),
    ("你去过中国吗", "Have you been to China?"),
    ("我去过北京", "I have been to Beijing"),
    ("你喜欢看书吗", "Do you like reading books?"),
    ("我喜欢看小说", "I like reading novels"),
    ("你有宠物吗", "Do you have any pets?"),
    ("我有一只狗", "I have a dog"),
    ("他正在工作", "He is working"),
    ("她在看电视", "She is watching TV"),
    ("你喜欢喝果汁吗", "Do you like drinking juice?"),
    ("我喜欢喝橙汁", "I like drinking orange juice"),
    ("你喜欢跑步还是游泳", "Do you like running or swimming?"),
    ("我喜欢跑步", "I like running"),
    ("你吃过早饭吗", "Did you have breakfast?"),
    ("我还没吃", "I haven't eaten yet"),
    ("你能帮我做这个吗", "Can you help me do this?"),
    ("我能帮你吗", "Can I help you?"),
    ("他在看电影", "He is watching a movie"),
    ("她喜欢听音乐", "She likes listening to music"),
    ("你会做蛋糕吗", "Can you bake a cake?"),
    ("我不会做蛋糕", "I can't bake a cake"),
    ("我需要休息一下", "I need to take a break"),
    ("今天我们去购物", "We will go shopping today"),
    ("你喜欢喝可乐吗", "Do you like drinking cola?"),
    ("我喜欢喝可乐", "I like drinking cola"),
    ("你想喝什么", "What do you want to drink?"),
    ("我想喝水", "I want to drink water"),
    ("你喜欢运动吗", "Do you like sports?"),
    ("我喜欢跑步", "I like running"),
    ("你会跳舞吗", "Can you dance?"),
    ("我会跳舞", "I can dance"),
    ("你有手机吗", "Do you have a phone?"),
    ("我没有手机", "I don't have a phone"),
    ("我爱俄罗斯", "I love Russia"),
    ("我爱印度", "I love India"),
    ("我爱巴西", "I love Brazil"),
    ("我爱阿根廷", "I love Argentina"),
    ("我爱墨西哥", "I love Mexico"),
    ("我喜欢看电视剧", "I like watching TV shows"),
    ("你会做手工吗", "Can you do handicrafts?"),
    ("我会做手工", "I can do handicrafts"),
    ("你喜欢拍照吗", "Do you like taking photos?"),
    ("我喜欢拍照", "I like taking photos"),
    ("你喜欢早上还是晚上", "Do you like mornings or evenings?"),
    ("我喜欢早上", "I like mornings"),
    ("你喜欢吃火锅吗", "Do you like eating hotpot?"),
    ("我喜欢吃火锅", "I like eating hotpot"),
    ("你能给我你的邮箱吗", "Can you give me your email?"),
    ("我的邮箱是123@example.com", "My email is 123@example.com"),
    ("你喜欢跑步吗", "Do you like running?"),
    ("我喜欢跑步", "I like running"),
    ("今天是个特别的日子", "Today is a special day"),
    ("她正在学习英语", "She is learning English"),
    ("你想吃点心吗", "Do you want to eat some snacks?"),
    ("我正在读一本小说", "I am reading a novel"),
    ("他喜欢打乒乓球", "He likes playing table tennis"),
    ("你什么时候去旅行", "When are you going to travel?"),
    ("我早上七点起床", "I wake up at 7 in the morning"),
    ("我们可以一起去吃饭吗", "Can we go to eat together?"),
    ("这本书是我借的", "This book is borrowed by me"),
    ("他的中文说得很好", "His Chinese is very good"),
    ("我想学游泳", "I want to learn swimming"),
    ("你想要喝点什么", "What would you like to drink?"),
    ("他很喜欢学习", "He loves studying"),
    ("你喜欢什么样的音乐", "What kind of music do you like?"),
    ("我喜欢古典音乐", "I like classical music"),
    ("他正在跑步", "He is running"),
    ("你今天做了什么", "What did you do today?"),
    ("我去超市买了东西", "I went to the supermarket and bought something"),
    ("他在家休息", "He is resting at home"),
    ("我今天早上去了银行", "I went to the bank this morning"),
    ("你可以帮我做这件事吗", "Can you help me with this?"),
    ("我正在考虑这个问题", "I am thinking about this problem"),
    ("他今天不在", "He is not here today"),
    ("你今天早上喝了咖啡吗", "Did you drink coffee this morning?"),
    ("我喝了咖啡", "I drank coffee"),
    ("这部电影我看过", "I have seen this movie"),
    ("你喜欢去海滩吗", "Do you like going to the beach?"),
    ("我很喜欢去海滩", "I really like going to the beach"),
    ("他每天都跑步", "He runs every day"),
    ("我觉得这道题很难", "I think this question is difficult"),
    ("她在商店工作", "She works at the store"),
    ("你会做什么运动", "What sports can you do?"),
    ("我爱南非", "I love South Africa"),
    ("我爱韩国", "I love South Korea"),
    ("我爱新加坡", "I love Singapore"),
    ("我爱瑞士", "I love Switzerland"),
    ("我爱瑞典", "I love Sweden"),
    ("我会打羽毛球", "I can play badminton"),
    ("他喜欢画画", "He likes painting"),
    ("你常常去旅游吗", "Do you travel often?"),
    ("我每年都去旅游", "I travel every year"),
    ("你是做什么工作的", "What is your job?"),
    ("我是软件工程师", "I am a software engineer"),
    ("她每天走路去上班", "She walks to work every day"),
    ("我住在城市中心", "I live in the city center"),
    ("你喜欢吃什么水果", "What fruit do you like to eat?"),
    ("我喜欢吃草莓", "I like eating strawberries"),
    ("你能帮我拍照吗", "Can you take a photo for me?"),
    ("我爱看电影", "I love watching movies"),
    ("我爱吃冰淇淋", "I love eating ice cream"),
    ("我爱旅行", "I love traveling"),
    ("我爱读书", "I love reading books"),
    ("我爱我的家人", "I love my family"),
    ("我爱喝茶", "I love drinking tea"),
    ("我爱狗", "I love dogs"),
    ("我爱猫", "I love cats"),
    ("我爱听音乐", "I love listening to music"),
    ("我爱运动", "I love sports"),
    ("我爱打篮球", "I love playing basketball"),
    ("我爱看书", "I love reading"),
    ("我爱吃水果", "I love eating fruits"),
    ("我爱吃辣", "I love eating spicy food"),
    ("我爱做饭", "I love cooking"),
    ("我爱我的工作", "I love my job"),
    ("我爱学习", "I love studying"),
    ("我爱我的朋友", "I love my friends"),
    ("我爱我的老师", "I love my teacher"),
    ("我爱做手工", "I love doing handicrafts"),
    ("我爱写作", "I love writing"),
    ("我爱喝咖啡", "I love drinking coffee"),
    ("我爱画画", "I love drawing"),
    ("我爱看动漫", "I love watching anime"),
    ("我爱跑步", "I love running"),
    ("我爱游泳", "I love swimming"),
    ("我爱看新闻", "I love watching the news"),
    ("我爱看球赛", "I love watching sports games"),
    ("我可以给你打电话", "I can call you"),
    ("她是我的同学", "She is my classmate"),
    ("我有很多朋友", "I have many friends"),
    ("你喜欢这本书吗", "Do you like this book?"),
    ("我觉得这本书很有趣", "I think this book is interesting"),
    ("我们去参加婚礼", "We are going to attend a wedding"),
    ("你喜欢吃辣吗", "Do you like spicy food?"),
    ("我喜欢吃辣", "I like spicy food"),
    ("我很高兴认识你", "I am happy to meet you"),
    ("明天我去旅行", "I am going traveling tomorrow"),
    ("你会做饭吗", "Can you cook?"),
    ("我会做一些简单的菜", "I can cook some simple dishes"),
    ("你可以教我做饭吗", "Can you teach me to cook?"),
    ("我很喜欢跑步", "I really like running"),
    ("他每天都锻炼", "He exercises every day"),
    ("你喜欢看书吗", "Do you like reading books?"),
    ("我喜欢看历史书", "I like reading history books"),
    ("你去过纽约吗", "Have you been to New York?"),
    ("我去过一次", "I have been there once"),
    ("你喜欢哪种电影", "What kind of movies do you like?"),
    ("我喜欢恐怖片", "I like horror movies"),
    ("你能帮我做作业吗", "Can you help me with my homework?"),
    ("我正在做作业", "I am doing my homework"),
    ("我在家休息", "I am resting at home"),
    ("我喜欢做运动", "I like doing sports"),
    ("你喜欢旅游吗", "Do you like traveling?"),
    ("我喜欢去不同的地方", "I like going to different places"),
    ("你今天早上吃了什么", "What did you eat this morning?"),
    ("我吃了一个三明治", "I ate a sandwich"),
    ("你喜欢喝果汁吗", "Do you like drinking juice?"),
    ("我喜欢喝苹果汁", "I like drinking apple juice"),
    ("你会说法语吗", "Can you speak French?"),
    ("我会一点法语", "I can speak a little French"),
    ("他在学习西班牙语", "He is learning Spanish"),
    ("你喜欢做什么运动", "What sports do you like to do?"),
    ("我喜欢打篮球", "I like playing basketball"),
    ("他喜欢骑自行车", "He likes riding a bike"),
    ("你去哪儿了", "Where have you been?"),
    ("我去超市买了东西", "I went to the supermarket to buy something"),
    ("我们可以去吃饭吗", "Can we go eat?"),
    ("你喜欢运动吗", "Do you like sports?"),
    ("我喜欢踢足球", "I like playing soccer"),
    ("你喜欢吃什么", "What do you like to eat?"),
    ("我喜欢吃意大利面", "I like eating pasta"),
    ("你喜欢跑步还是游泳", "Do you like running or swimming?"),
    ("我喜欢游泳", "I like swimming"),
    ("今天是一个美丽的日子", "Today is a beautiful day"),
    ("你喜欢听什么歌", "What songs do you like to listen to?"),
    ("我喜欢听流行歌", "I like listening to pop music"),
    ("你会做瑜伽吗", "Can you do yoga?"),
    ("我会做瑜伽", "I can do yoga"),
    ("我有很多兴趣爱好", "I have many hobbies"),
    ("你喜欢读什么类型的书", "What type of books do you like to read?"),
    ("我喜欢读科幻小说", "I like reading science fiction novels"),
    ("你喜欢喝什么茶", "What tea do you like to drink?"),
    ("我喜欢喝绿茶", "I like drinking green tea"),
    ("你喜欢看电影吗", "Do you like watching movies?"),
    ("我喜欢看动作片", "I like watching action movies"),
    ("今天我有很多事情要做", "I have a lot to do today"),
    ("你喜欢打篮球吗", "Do you like playing basketball?"),
    ("我喜欢打篮球", "I like playing basketball"),
    ("你在干什么", "What are you doing?"),
    ("我在看书", "I am reading a book"),
    ("你吃过午饭了吗", "Have you had lunch?"),
    ("我吃了午饭", "I have had lunch"),
    ("他每天都看新闻", "He watches the news every day"),
    ("我正在学习英语", "I am studying English"),
    ("他去健身房锻炼", "He goes to the gym to work out"),
    ("你喜欢做什么", "What do you like to do?"),
    ("我喜欢听音乐", "I like listening to music"),
    ("我正在看电视", "I am watching TV"),
    ("你喜欢什么颜色", "What color do you like?"),
    ("我喜欢红色", "I like red"),
    ("今天是我的生日", "Today is my birthday"),
    ("我去了一趟北京", "I went to Beijing"),
    ("你喜欢去哪些地方旅游", "Where do you like to travel?"),
    ("我喜欢去海滩", "I like going to the beach"),
    ("你会跳舞吗", "Can you dance?"),
    ("我会跳舞", "I can dance"),
    ("你做什么工作", "What do you do?"),
    ("我是一名医生", "I am a doctor"),
    ("你喜欢看哪些电影", "What movies do you like to watch?"),
    ("我喜欢看喜剧片", "I like watching comedy movies"),
    ("你每天几点起床", "What time do you wake up every day?"),
    ("我每天六点起床", "I wake up at six o'clock every day"),
    ("我喜欢冬天", "I like winter"),
    ("你今天有什么计划", "What plans do you have today?"),
    ("我想去购物", "I want to go shopping"),
    ("你喜欢喝咖啡还是茶", "Do you prefer coffee or tea?"),
    ("我喜欢喝茶", "I prefer tea"),
    ("你会说日语吗", "Can you speak Japanese?"),
    ("我会说一些日语", "I can speak some Japanese"),
    ("他在读一本杂志", "He is reading a magazine"),
    ("我在家做饭", "I am cooking at home"),
    ("你喜欢什么类型的运动", "What type of sports do you like?"),
    ("我喜欢跑步和游泳", "I like running and swimming"),
    ("你喜欢看电视吗", "Do you like watching TV?"),
    ("我喜欢看新闻", "I like watching the news"),
    ("你有宠物吗", "Do you have pets?"),
    ("我有一只猫", "I have a cat"),
    ("你想要做什么工作", "What job would you like to do?"),
    ("我想成为医生", "I want to be a doctor"),
    ("你今天怎么了", "What's wrong with you today?"),
    ("我今天很累", "I am very tired today"),
    ("你喜欢吃什么菜", "What dishes do you like to eat?"),
    ("我喜欢吃中餐", "I like eating Chinese food"),
    ("你会说多少种语言", "How many languages can you speak?"),
    ("我会说三种语言", "I can speak three languages"),
    ("你吃过早饭了吗", "Have you had breakfast?"),
    ("我还没吃早饭", "I haven't had breakfast yet"),
    ("我们一起去看电影吧", "Let's go to the movies together"),
    ("你喜欢什么颜色的衣服", "What color of clothes do you like?"),
    ("我喜欢穿蓝色的衣服", "I like wearing blue clothes"),
    ("你住在什么地方", "Where do you live?"),
    ("我住在郊区", "I live in the suburbs"),
    ("他在打电话", "He is on the phone"),
    ("我正在写信", "I am writing a letter"),
    ("你喜欢做什么运动", "What sports do you like to do?"),
    ("我喜欢打网球", "I like playing tennis"),
    ("你觉得这件衣服怎么样", "What do you think of this clothing?"),
    ("我觉得它很漂亮", "I think it is beautiful"),
    ("今天的天气很好", "The weather is nice today"),
    ("我们一起去公园散步吧", "Let's go for a walk in the park"),
    ("你喜欢养什么宠物", "What pets do you like to keep?"),
    ("我喜欢养狗", "I like keeping dogs"),
    ("你平时喜欢做什么", "What do you usually like to do?"),
    ("我喜欢听音乐和看电影", "I like listening to music and watching movies"),
    ("你住在哪里", "Where do you live?"),
    ("我住在上海", "I live in Shanghai"),
    ("你喜欢看哪些类型的电影", "What type of movies do you like to watch?"),
    ("我喜欢科幻片和动作片", "I like science fiction and action movies"),
    ("我喜欢去海边度假", "I like to go on vacation to the beach"),
    ("你学英语多久了", "How long have you been learning English?"),
    ("我学英语已经三年了", "I have been learning English for three years"),
    ("你喜欢做饭吗", "Do you like cooking?"),
    ("我喜欢做饭", "I like cooking"),
    ("你会弹吉他吗", "Can you play the guitar?"),
    ("我会弹吉他", "I can play the guitar"),
    ("你常去健身房吗", "Do you go to the gym often?"),
    ("我每天都去健身房", "I go to the gym every day"),
    ("你喜欢吃水果吗", "Do you like eating fruits?"),
    ("我喜欢吃苹果和香蕉", "I like eating apples and bananas"),
    ("你今天有空吗", "Are you free today?"),
    ("我今天有空", "I am free today"),
    ("你喜欢运动吗", "Do you like sports?"),
    ("我喜欢跑步和游泳", "I like running and swimming"),
    ("你会游泳吗", "Can you swim?"),
    ("我不会游泳", "I can't swim"),
    ("你喜欢做什么", "What do you like to do?"),
    ("我喜欢读书和听音乐", "I like reading books and listening to music"),
    ("你喜欢旅行吗", "Do you like traveling?"),
    ("我喜欢旅行", "I like traveling"),
    ("她正在学习烹饪技巧", "She is learning cooking skills"),
    ("我的朋友们总是让我笑", "My friends always make me laugh"),
    ("我们在学校里有一个很好的篮球队", "We have a great basketball team at school"),
    ("她最近搬到了新的住所", "She recently moved to a new place"),
    ("我计划明天去爬山", "I plan to go hiking tomorrow"),
    ("他每天都花时间和家人相处", "He spends time with his family every day"),
    ("我对这项新工作充满期待", "I am looking forward to this new job"),
    ("我们喜欢在周末做家庭聚会", "We like having family gatherings on weekends"),
    ("她总是能找到解决问题的方法", "She always finds a way to solve problems"),
    ("我喜欢在晚上散步，思考一天的事情", "I like to walk at night and think about the day's events"),
    ("他是一个非常有耐心的人", "He is a very patient person"),
    ("她每天都会写日记", "She writes in her journal every day"),
    ("我准备为下个月的考试复习", "I am preparing for next month's exam"),
    ("我们去的那个餐厅特别安静", "The restaurant we went to was very quiet"),
    ("他正在学习如何弹钢琴", "He is learning how to play the piano"),
    ("我在大学里学了很多有趣的课程", "I took many interesting courses in college"),
    ("她最近迷上了跳舞", "She recently became obsessed with dancing"),
    ("这本书让我感受到了深深的启发", "This book inspired me deeply"),
    ("他总是积极地帮助别人", "He is always eager to help others"),
    ("我们决定去海边度假", "We decided to go to the beach for a vacation"),
    ("我最近养了一只猫", "I recently adopted a cat"),
    ("他从不迟到", "He is never late"),
    ("我的家里有一只可爱的狗", "I have a cute dog at home"),
    ("他们刚刚搬到了新家", "They just moved to a new house"),
    ("我喜欢晚上看书，享受宁静的时光", "I like reading at night, enjoying the quiet time"),
    ("我最近开始做冥想", "I recently started doing meditation"),
    ("我们一家人计划今年去日本旅游", "Our family plans to travel to Japan this year"),
    ("她喜欢在周末去逛街", "She likes to go shopping on weekends"),
    ("我的爸爸是一名医生", "My dad is a doctor"),
    ("我们班有很多国际学生", "There are many international students in our class"),
    ("我最近学会了做寿司", "I recently learned how to make sushi"),
    ("他是一个非常有才华的画家", "He is a very talented artist"),
    ("我们去年去了欧洲旅行", "We traveled to Europe last year"),
    ("我喜欢在晚上跑步", "I like running at night"),
    ("她有很多漂亮的衣服", "She has many beautiful clothes"),
    ("我家附近有一个很大的购物中心", "There is a big shopping mall near my house"),
    ("我最近开始学游泳", "I recently started learning how to swim"),
    ("我们打算明年去澳大利亚旅游", "We plan to travel to Australia next year"),
    ("我对这个项目很感兴趣", "I am very interested in this project"),
    ("他每天都会去健身房锻炼", "He goes to the gym every day to work out"),
    ("我最近加入了一个跑步小组", "I recently joined a running group"),
    ("我喜欢每个周末做不同的活动", "I like doing different activities every weekend"),
    ("他是我的大学同学", "He is my classmate from college"),
    ("这座城市的夜景很美", "The night view of this city is beautiful"),
    ("我有一个喜欢做手工艺的朋友", "I have a friend who loves doing crafts"),
    ("她每天都会做瑜伽", "She does yoga every day"),
    ("我最近刚学会骑自行车", "I recently learned how to ride a bike"),
    ("他们计划在夏天去海滩度假", "They plan to go to the beach for a vacation in the summer"),
    ("我喜欢在安静的地方读书", "I like reading in quiet places"),
    ("今天的会议非常顺利", "Today's meeting went very smoothly"),
    ("你喜欢去哪个国家", "Which country do you like to visit?"),
    ("我喜欢去日本", "I like visiting Japan"),
    ("你喜欢哪种运动", "What kind of sport do you like?"),
    ("我喜欢足球和篮球", "I like soccer and basketball"),
    ("你有兄弟姐妹吗", "Do you have any siblings?"),
    ("我有两个兄弟", "I have two brothers"),
    ("你喜欢去哪里玩", "Where do you like to go for fun?"),
    ("我喜欢去博物馆", "I like going to museums"),
    ("你在做什么", "What are you doing?"),
    ("我在看书", "I am reading a book"),
    ("你喜欢哪种类型的书", "What type of books do you like?"),
    ("我喜欢小说和历史书", "I like novels and history books"),
    ("你喜欢用什么交通工具", "What mode of transportation do you prefer?"),
    ("我喜欢坐地铁", "I prefer taking the subway"),
    ("你有什么兴趣爱好", "What are your hobbies?"),
    ("我喜欢看电影和旅行", "I like watching movies and traveling"),
    ("你喜欢去游乐园吗", "Do you like going to amusement parks?"),
    ("我喜欢去游乐园", "I like going to amusement parks"),
    ("你常做运动吗", "Do you exercise regularly?"),
    ("我每天都会做运动", "I exercise every day"),
    ("你喜欢喝什么饮料", "What drink do you like?"),
    ("我喜欢喝果汁", "I like drinking fruit juice"),
    ("你喜欢哪种花", "What type of flowers do you like?"),
    ("我喜欢玫瑰", "I like roses"),
    ("你喜欢冬天还是夏天", "Do you prefer winter or summer?"),
    ("我喜欢夏天", "I prefer summer"),
    ("你喜欢喝啤酒吗", "Do you like drinking beer?"),
    ("我不喜欢喝啤酒", "I don't like drinking beer"),
    ("你喜欢吃中餐还是西餐", "Do you prefer Chinese food or Western food?"),
    ("我喜欢吃中餐", "I prefer Chinese food"),
    ("你做什么工作", "What do you do for work?"),
    ("我是一名教师", "I am a teacher"),
    ("你喜欢看足球比赛吗", "Do you like watching football matches?"),
    ("我喜欢看足球比赛", "I like watching football matches"),
    ("你吃过午饭了吗", "Have you had lunch?"),
    ("我已经吃过了", "I have already had lunch"),
    ("你喜欢运动吗", "Do you like sports?"),
    ("我喜欢运动", "I like sports"),
    ("你喜欢什么样的音乐", "What kind of music do you like?"),
    ("我喜欢摇滚乐", "I like rock music"),
    ("你喜欢去哪里度假", "Where do you like to go on vacation?"),
    ("我喜欢去海边", "I like going to the beach"),
    ("你喜欢看电视吗", "Do you like watching TV?"),
    ("我喜欢看电影", "I like watching movies"),
    ("你有什么特别的爱好吗", "Do you have any special hobbies?"),
    ("我喜欢摄影", "I like photography"),
    ("你喜欢吃什么", "What do you like to eat?"),
    ("我喜欢吃汉堡", "I like eating hamburgers"),
    ("你喜欢做饭吗", "Do you like cooking?"),
    ("我喜欢做饭", "I like cooking"),
    ("你喜欢什么运动", "What sport do you like?"),
    ("我喜欢打羽毛球", "I like playing badminton"),
    ("你住在什么地方", "Where do you live?"),
    ("我住在城市里", "I live in the city"),
    ("你有多少个朋友", "How many friends do you have?"),
    ("我有很多朋友", "I have many friends"),
    ("我喜欢玩游戏", "I like playing games"),
    ("你会说中文吗", "Can you speak Chinese?"),
    ("我能帮你吗", "Can I help you?"),
    ("你想要什么", "What do you want?"),
    ("我正在工作", "I am working"),
    ("你今天感觉怎么样", "How do you feel today?"),
    ("我觉得很好", "I feel great"),
    ("我爱吃烧烤", "I love eating barbecue"),
    ("我爱看舞蹈", "I love watching dance"),
    ("我爱弹钢琴", "I love playing the piano"),
    ("我爱看恐怖片", "I love watching horror movies"),
    ("我爱打游戏", "I love playing games"),
    ("我爱旅游", "I love traveling"),
    ("我爱爬山", "I love hiking"),
    ("我爱喝可乐", "I love drinking cola"),
    ("我爱喝酸奶", "I love drinking yogurt"),
    ("我爱吃面包", "I love eating bread"),
    ("我爱去博物馆", "I love going to museums"),
    ("我爱挑战自己", "I love challenging myself"),
    ("我爱看书法", "I love watching calligraphy"),
    ("我爱看魔术", "I love watching magic tricks"),
    ("我爱看歌剧", "I love watching opera"),
    ("我爱看话剧", "I love watching plays"),
    ("我爱看纪录片", "I love watching documentaries"),
    ("我爱看动画片", "I love watching cartoons"),
    ("我爱吃牛排", "I love eating steak"),
    ("我爱吃煎饼果子", "I love eating Jianbing"),
    ("我爱吃鸭脖", "I love eating duck neck"),
    ("我爱吃烤肉", "I love eating barbecue"),
    ("我爱吃牛肉", "I love eating beef"),
    ("我爱吃猪肉", "I love eating pork"),
    ("我爱吃鸡肉", "I love eating chicken"),
    ("我爱吃火腿", "I love eating ham"),
    ("我爱喝绿茶", "I love drinking green tea"),
    ("我爱喝白开水", "I love drinking plain water"),
    ("我爱烘焙", "I love baking"),
    ("我爱做DIY", "I love doing DIY projects"),
    ("我爱做家务", "I love doing housework"),
    ("我爱去健身房", "I love going to the gym"),
    ("我爱做运动", "I love exercising"),
    ("我爱做早操", "I love doing morning exercises"),
    ("我爱做冥想", "I love doing meditation"),
    ("我爱看漫画", "I love reading comics"),
    ("我爱听故事", "I love listening to stories"),
    ("我爱做早餐", "I love making breakfast"),
    ("我爱吃中餐", "I love eating Chinese food"),
    ("我爱吃西餐", "I love eating Western food"),
    ("我爱去餐馆", "I love going to restaurants"),
    ("我爱照顾宠物", "I love taking care of pets"),
    ("我爱写信", "I love writing letters"),
    ("我爱拼图", "I love doing puzzles"),
    ("我爱做手链", "I love making bracelets"),
    ("我爱玩滑板", "I love skateboarding"),
    ("我爱摄影", "I love photography"),
    ("我爱做陶艺", "I love doing pottery"),
    ("我爱做手工艺", "I love doing crafts"),
    ("我爱滑雪", "I love skiing"),
    ("我爱跳舞", "I love dancing"),
    ("我爱写程序", "I love coding"),
    ("我爱玩扑克", "I love playing poker"),
    ("我爱做游戏设计", "I love doing game design"),
    ("我爱收集玩具", "I love collecting toys"),
    ("我爱养植物", "I love growing plants"),
    ("我爱做瑜伽", "I love doing yoga"),
    ("我爱练武术", "I love practicing martial arts"),
    ("我爱编程", "I love programming"),
    ("我爱看旅游视频", "I love watching travel videos"),
    ("我爱学新语言", "I love learning new languages"),
    ("我爱养宠物", "I love keeping pets"),
    ("我爱做陶艺", "I love doing pottery"),
    ("我爱看历史书", "I love reading history books"),
    ("我爱品茶", "I love tasting tea"),
    ("我爱照相", "I love taking photos"),
    ("我爱看喜剧", "I love watching comedies"),
    ("我爱学习新事物", "I love learning new things"),
    ("我爱做实验", "I love doing experiments"),
    ("我每年都去拜访我的祖父母", "I visit my grandparents every year"),
    ("她最近迷上了做甜点", "She recently became obsessed with making desserts"),
    ("我们决定去参加一个朋友的婚礼", "We decided to attend a friend's wedding"),
    ("我最近看了一部很棒的电影", "I recently watched a great movie"),
    ("他正在为他的项目做研究", "He is doing research for his project"),
    ("我喜欢和家人一起做饭", "I like cooking with my family"),
    ("这本书很适合晚上阅读", "This book is perfect for reading at night"),
    ("我正在学习如何修理汽车", "I am learning how to repair cars"),
    ("她每天都跑步五公里", "She runs five kilometers every day"),
    ("我们正在筹划一个生日派对", "We are planning a birthday party"),
    ("我喜欢安静的环境", "I like quiet environments"),
    ("他最近参加了一个烹饪课程", "He recently attended a cooking class"),
    ("我们去过很多国家旅游", "We have traveled to many countries"),
    ("她是我最好的朋友", "She is my best friend"),
    ("我每天都学习英语", "I study English every day"),
    ("这座公园里有很多树", "There are many trees in this park"),
    ("我正在学习如何打高尔夫球", "I am learning how to play golf"),
    ("我们计划在秋天去看枫叶", "We plan to see the maple leaves in autumn"),
    ("今天我在家休息", "I am resting at home today"),
    ("他在咖啡店里工作", "He works in a café"),
    ("她正在阅读一本新的小说", "She is reading a new novel"),
    ("我们全家一起度过了一个愉快的假期", "Our family spent a pleasant holiday together"),
    ("我喜欢拍摄风景照片", "I enjoy taking landscape photos"),
    ("今天我做了一个大决定", "I made a big decision today"),
    ("我们每年都会去看一次烟花表演", "We go to see fireworks every year"),
    ("他今天穿了一件红色的衬衫", "He wore a red shirt today"),
    ("我打算去参加一个音乐会", "I plan to attend a concert"),
    ("他们家有一个很大的花园", "They have a big garden at their house"),
    ("我喜欢用钢笔写字", "I like writing with a fountain pen"),
    ("今天是我的生日", "Today is my birthday"),
    ("他做事非常有条理", "He is very organized"),
    ("我正在读一本关于心理学的书", "I am reading a book about psychology"),
    ("我们在海滩上度过了一个美好的下午", "We spent a wonderful afternoon at the beach"),
    ("我正在学习如何做木工", "I am learning how to do woodworking"),
    ("我最近喜欢看纪录片", "I recently enjoy watching documentaries"),
    ("他是一位非常有经验的教师", "He is a very experienced teacher"),
    ("她每天都喝两杯水", "She drinks two cups of water every day"),
    ("我正在尝试新的健身计划", "I am trying a new fitness plan"),
    ("他们家有一只非常聪明的猫", "They have a very smart cat at home"),
    ("我今天学到了一些新技能", "I learned some new skills today"),
    ("我喜欢做手工艺品", "I like making crafts"),
    ("他正在准备一次重要的考试", "He is preparing for an important exam"),
    ("她爱好画画", "She enjoys painting"),
    ("我们计划下个月去看雪", "We plan to go see snow next month"),
    ("他今天去买了新衣服", "He went to buy new clothes today"),
    ("我喜欢在周末做早餐", "I like making breakfast on weekends"),
    ("她是一个非常有创意的人", "She is a very creative person"),
    ("我们准备为朋友举办一场派对", "We are preparing to host a party for our friend"),
    ("我今天早上去了超市", "I went to the supermarket this morning"),
    ("他们的车库里有很多工具", "There are many tools in their garage"),
    ("我正在学习新的烹饪技巧", "I am learning new cooking skills"),
    ("我们决定一起去看日出", "We decided to go watch the sunrise together"),
    ("她喜欢参加运动比赛", "She likes to participate in sports competitions"),
    ("我买了一些新书", "I bought some new books"),
    ("我正在考虑换一份工作", "I am considering changing jobs"),
    ("我喜欢和朋友一起去海滩", "I like going to the beach with my friends"),
    ("他非常喜欢养花", "He really enjoys gardening"),
    ("她今天穿了一条蓝色的裙子", "She wore a blue dress today"),
    ("我每天都喝很多水", "I drink a lot of water every day"),
    ("我们今年夏天去度假", "We are going on vacation this summer"),
    ("他总是积极地面对挑战", "He always faces challenges positively"),
    ("我喜欢独自一人散步", "I enjoy walking alone"),
    ("今天我做了一顿简单的晚餐", "I made a simple dinner today"),
    ("她去健身房保持健康", "She goes to the gym to stay healthy"),
    ("我们每天都一起吃午餐", "We have lunch together every day"),
    ("他买了一个新背包", "He bought a new backpack"),
    ("我每天都做一些运动", "I do some exercise every day"),
    ("他们正在举办一个音乐节", "They are hosting a music festival"),
    ("我喜欢在家里待着", "I like staying at home"),
    ("他最近学会了做披萨", "He recently learned how to make pizza"),
    ("我们决定尝试新的餐厅", "We decided to try a new restaurant"),
    ("她正在读一本很有意思的书", "She is reading a very interesting book"),
    ("我们计划去参观博物馆", "We plan to visit the museum"),
    ("我今天没有去工作", "I didn't go to work today"),
    ("他总是保持微笑", "He always keeps a smile on his face"),
    ("我今天和朋友一起去散步", "I went for a walk with my friends today"),
    ("她最近开始学做饭", "She recently started learning how to cook"),
    ("我喜欢去海边度假", "I love vacationing at the beach"),
    ("我们最近换了家里的一些家具", "We recently changed some furniture in the house"),
    ("他今天买了一个新手机", "He bought a new phone today"),
    ("我爱设计", "I love designing"),
    ("我爱拍视频", "I love shooting videos"),
    ("我爱学习编程", "I love learning programming"),
    ("我爱听广播", "I love listening to the radio"),
    ("我爱集邮", "I love stamp collecting"),
    ("我爱学做菜", "I love learning to cook"),
    ("我每天都读一些新闻", "I read some news every day"),
    ("她最近开始做瑜伽", "She recently started doing yoga"),
    ("我们在公园里玩得很开心", "We had a great time playing in the park"),
    ("我最近学会了做饺子", "I recently learned how to make dumplings"),
    ("他喜欢收藏邮票", "He likes collecting stamps"),
    ("我们家有一只可爱的小狗", "We have a cute little dog at home"),
    ("她最近学会了游泳", "She recently learned how to swim"),
    ("我今天买了几件新衣服", "I bought a few new clothes today"),
    ("他们正在修建一座新桥", "They are building a new bridge"),
    ("我喜欢在家里做瑜伽", "I like doing yoga at home"),
    ("我今天和朋友一起看了电影", "I watched a movie with my friend today"),
    ("他最近买了一辆新车", "He recently bought a new car"),
    ("我正在学习新的烹饪技巧", "I am learning new cooking techniques"),
    ("她每天都会喝绿茶", "She drinks green tea every day"),
    ("我们一起做了很多准备工作", "We did a lot of preparations together"),
    ("我喜欢在晚上跑步", "I like running at night"),
    ("他们刚搬进了新家", "They just moved into a new house"),
    ("我每天都喝一杯咖啡", "I drink a cup of coffee every day"),
    ("他今天去参加了一个讲座", "He attended a lecture today"),
    ("我们计划去参加婚礼", "We plan to attend a wedding"),
    ("她喜欢跳舞", "She likes dancing"),
    ("我正在学习如何做甜点", "I am learning how to make desserts"),
    ("他们家有一个大花园", "They have a big garden at home"),
    ("我每天都会做运动", "I exercise every day"),
    ("他是一个非常细心的人", "He is a very careful person"),
    ("我今天去买了些水果", "I went to buy some fruits today"),
    ("她喜欢旅行", "She likes to travel"),
    ("我爱参加活动", "I love participating in activities"),
    ("我爱和朋友聚会", "I love hanging out with friends"),
    ("我爱做手工艺品", "I love making crafts"),
    ("我爱做手工饰品", "I love making handmade jewelry"),
    ("我爱参加派对", "I love attending parties"),
    ("我爱参加比赛", "I love participating in competitions"),
    ("我爱参与公益活动", "I love participating in charity activities"),
    ("我爱收藏书籍", "I love collecting books"),
    ("我爱研究新技术", "I love researching new technologies"),
    ("明天我们去爬山", "We will go hiking tomorrow"),
    ("你喜欢看体育吗", "Do you like watching sports?"),
    ("我喜欢看篮球比赛", "I like watching basketball games"),
    ("你会打乒乓球吗", "Can you play table tennis?"),
    ("我会打乒乓球", "I can play table tennis"),
    ("你喜欢吃炸鸡吗", "Do you like eating fried chicken?"),
    ("我喜欢吃炸鸡", "I like eating fried chicken"),
    ("你什么时候放假", "When do you have a holiday?"),
    ("我下周放假", "I have a holiday next week"),
    ("你能告诉我时间吗", "Can you tell me the time?"),
    ("现在是三点", "It is 3 o'clock now"),
    ("你今天很忙吗", "Are you busy today?"),
    ("今天我不忙", "I am not busy today"),
    ("我很喜欢看漫画", "I really like reading comics"),
    ("你喜欢去博物馆吗", "Do you like going to museums?"),
    ("我喜欢去博物馆", "I like going to museums"),
    ("你今天做了什么", "What did you do today?"),
    ("我去买了衣服", "I went to buy clothes"),
    ("你喜欢什么样的电影", "What kind of movies do you like?"),
    ("我喜欢爱情电影", "I like romantic movies"),
    ("你会打篮球吗", "Can you play basketball?"),
    ("我会打篮球", "I can play basketball"),
    ("今天是一个特别的日子", "Today is a special day"),
    ("他正在准备考试", "He is preparing for the exam"),
    ("你喜欢喝水还是果汁", "Do you prefer water or juice?"),
    ("我喜欢喝水", "I prefer drinking water"),
    ("我在看新闻", "I am watching the news"),
    ("你喜欢看新闻吗", "Do you like watching the news?"),
    ("我喜欢吃水果", "I like eating fruits"),
    ("你喜欢吃西瓜吗", "Do you like eating watermelon?"),
    ("我喜欢吃西瓜", "I like eating watermelon"),
    ("你去过哪些国家", "Which countries have you been to?"),
    ("我去过美国和法国", "I have been to the United States and France"),
    ("你今天要做什么", "What are you going to do today?"),
    ("我今天要去健身", "I am going to the gym today"),
    ("你喜欢看动漫吗", "Do you like watching anime?"),
    ("我喜欢看动漫", "I like watching anime"),
    ("你会做什么菜", "What dishes can you cook?"),
    ("我会做炒饭", "I can cook fried rice"),
    ("你喜欢看足球吗", "Do you like watching soccer?"),
    ("我喜欢看足球比赛", "I like watching soccer games"),
    ("你想去哪儿旅游", "Where do you want to travel?"),
    ("我想去欧洲", "I want to go to Europe"),
    ("你喜欢早上还是晚上", "Do you prefer mornings or evenings?"),
    ("我喜欢晚上", "I prefer evenings"),
    ("你今天很忙吗", "Are you busy today?"),
    ("我今天不忙", "I am not busy today"),
    ("你会做数学题吗", "Can you solve math problems?"),
    ("我可以帮你", "I can help you"),
    ("你能给我点建议吗", "Can you give me some advice?"),
    ("我建议你去旅行", "I suggest you go traveling"),
    ("你喜欢喝什么茶", "What tea do you like to drink?"),
    ("我喜欢喝绿茶", "I like drinking green tea"),
    ("你喜欢做运动吗", "Do you like doing sports?"),
    ("我喜欢游泳", "I like swimming"),
    ("你喜欢骑自行车吗", "Do you like riding a bike?"),
    ("我喜欢骑自行车", "I like riding a bike"),
    ("你喜欢吃面条吗", "Do you like eating noodles?"),
    ("我喜欢吃面条", "I like eating noodles"),
    ("你会做饺子吗", "Can you make dumplings?"),
    ("我会做饺子", "I can make dumplings"),
    ("你喜欢去哪儿度假", "Where do you like to go for vacation?"),
    ("我喜欢去海边", "I like going to the beach"),
    ("你喜欢骑马吗", "Do you like riding horses?"),
    ("我喜欢骑马", "I like riding horses"),
    ("你喜欢吃什么水果", "What fruit do you like to eat?"),
    ("我喜欢吃葡萄", "I like eating grapes"),
    ("你喜欢做饭吗", "Do you like cooking?"),
    ("我喜欢做饭", "I like cooking"),
    ("你会画画吗", "Can you draw?"),
    ("我会画画", "I can draw"),
    ("你喜欢跑步吗", "Do you like running?"),
    ("我喜欢跑步", "I like running"),
    ("你喜欢听音乐吗", "Do you like listening to music?"),
    ("我喜欢听音乐", "I like listening to music"),
    ("你喜欢做手工吗", "Do you like doing handicrafts?"),
    ("我喜欢做手工", "I like doing handicrafts"),
    ("你喜欢看电影吗", "Do you like watching movies?"),
    ("我喜欢看电影", "I like watching movies"),
    ("你会说英语吗", "Can you speak English?"),
    ("我会说一点英语", "I can speak a little English"),
    ("你喜欢吃什么", "What do you like to eat?"),
    ("我喜欢吃鸡肉", "I like eating chicken"),
    ("你喜欢看什么类型的电影", "What type of movies do you like to watch?"),
    ("我喜欢动作片", "I like action movies"),
    ("你喜欢吃巧克力吗", "Do you like eating chocolate?"),
    ("我喜欢吃巧克力", "I like eating chocolate"),
    ("你喜欢喝咖啡吗", "Do you like drinking coffee?"),
    ("我喜欢喝咖啡", "I like drinking coffee"),
    ("你喜欢吃什么零食", "What snacks do you like to eat?"),
    ("我喜欢吃薯片", "I like eating potato chips"),
    ("你喜欢旅游吗", "Do you like traveling?"),
    ("我喜欢旅游", "I like traveling"),
    ("你喜欢看什么书", "What books do you like to read?"),
    ("我喜欢看小说", "I like reading novels"),
    ("你会游泳吗", "Can you swim?"),
    ("我会游泳", "I can swim"),
    ("你喜欢什么动物", "What animals do you like?"),
    ("我喜欢猫", "I like cats"),
    ("你会做蛋糕吗", "Can you bake a cake?"),
    ("我会做蛋糕", "I can bake a cake"),
    ("你喜欢喝茶吗", "Do you like drinking tea?"),
    ("我喜欢喝茶", "I like drinking tea"),
    ("你喜欢看新闻吗", "Do you like watching the news?"),
    ("我喜欢看新闻", "I like watching the news"),
    ("你喜欢吃什么甜点", "What desserts do you like to eat?"),
    ("我喜欢吃冰淇淋", "I like eating ice cream"),
    ("你喜欢什么季节", "What season do you like?"),
    ("我喜欢秋天", "I like autumn"),
    ("你喜欢吃披萨吗", "Do you like eating pizza?"),
    ("我喜欢吃披萨", "I like eating pizza"),
    ("你会做手指饼干吗", "Can you make finger biscuits?"),
    ("我会做手指饼干", "I can make finger biscuits"),
    ("你喜欢跑步还是游泳", "Do you like running or swimming?"),
    ("我喜欢游泳", "I like swimming"),
    ("你喜欢吃烤肉吗", "Do you like eating barbecue?"),
    ("我喜欢吃烤肉", "I like eating barbecue"),
    ("你喜欢喝什么饮料", "What drink do you like?"),
    ("我喜欢喝可乐", "I like drinking cola"),
    ("你喜欢看什么类型的书", "What type of books do you like to read?"),
    ("我喜欢看科幻书", "I like reading science fiction books"),
    ("你喜欢看漫画吗", "Do you like reading comics?"),
    ("我喜欢看漫画", "I like reading comics"),
    ("你喜欢吃饺子吗", "Do you like eating dumplings?"),
    ("我喜欢吃饺子", "I like eating dumplings"),
    ("你喜欢吃什么水果", "What fruits do you like to eat?"),
    ("我喜欢吃苹果", "I like eating apples"),
    ("你喜欢吃巧克力吗", "Do you like eating chocolate?"),
    ("我喜欢吃巧克力", "I like eating chocolate")
]



# ----------------------------------------
# 2. 数据预处理：Tokenizer编码
# ----------------------------------------
def encode_data(data, tokenizer, max_length=32):
    """
    对中文和英文翻译数据进行tokenize处理，返回模型输入和目标。
    """
    inputs, targets = [], []
    for src, tgt in data:
        input_ids = tokenizer(src, return_tensors="pt", padding='max_length', truncation=True,
                              max_length=max_length).input_ids
        target_ids = tokenizer(tgt, return_tensors="pt", padding='max_length', truncation=True,
                               max_length=max_length).input_ids
        inputs.append(input_ids.squeeze(0))
        targets.append(target_ids.squeeze(0))
    return inputs, targets


# 加载tokenizer
tokenizer = BartTokenizer.from_pretrained('pre_model/bert-base')
inputs, targets = encode_data(data, tokenizer)


# ----------------------------------------
# 3. 自定义数据集类
# ----------------------------------------
class TranslationDataset(Dataset):
    """
    数据集类，用于提供中文和英文对的数据。
    """

    def __init__(self, inputs, targets):
        self.inputs = inputs
        self.targets = targets

    def __len__(self):
        return len(self.inputs)

    def __getitem__(self, idx):
        return {'input_ids': self.inputs[idx], 'labels': self.targets[idx]}


# 创建数据加载器
train_dataset = TranslationDataset(inputs, targets)
train_dataloader = DataLoader(train_dataset, batch_size=2, shuffle=True)

# ----------------------------------------
# 4. 模型定义与配置
# ----------------------------------------
model = BartForConditionalGeneration.from_pretrained("pre_model/bert-base")

# 损失函数（交叉熵损失）
criterion = torch.nn.CrossEntropyLoss()

# AdamW优化器
optimizer = AdamW(model.parameters(), lr=5e-5)

# ----------------------------------------
# 5. 训练过程
# ----------------------------------------
# 将模型移到GPU（如果有的话）
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

epochs = 50
for epoch in range(epochs):
    model.train()
    running_loss = 0.0

    # 使用tqdm显示训练进度条
    for batch in tqdm(train_dataloader, desc=f"Epoch {epoch + 1}/{epochs}", ncols=100):
        input_ids = batch['input_ids'].to(device)
        labels = batch['labels'].to(device)

        # 前向传播
        outputs = model(input_ids=input_ids, labels=labels)
        loss = outputs.loss

        # 反向传播和优化
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch [{epoch + 1}/{epochs}], Loss: {running_loss / len(train_dataloader)}")

# ----------------------------------------
# 6. 保存训练后的模型
# ----------------------------------------
model.save_pretrained("./translation_model")
tokenizer.save_pretrained("./translation_model")


# ----------------------------------------
# 7. 翻译功能
# ----------------------------------------
def translate(text, model, tokenizer, device, max_length=32):
    """
    输入中文文本，输出英文翻译。
    """
    model.eval()
    inputs = tokenizer(text, return_tensors="pt", padding='max_length', truncation=True,
                       max_length=max_length).input_ids
    inputs = inputs.to(device)

    # 生成翻译结果
    with torch.no_grad():
        outputs = model.generate(inputs, max_length=max_length, num_beams=4, early_stopping=True)

    # 解码并返回翻译结果
    translated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return translated_text


# ----------------------------------------
# 8. 测试翻译功能
# ----------------------------------------
test_sentence = "我爱中国"
translated_sentence = translate(test_sentence, model, tokenizer, device)
print(f"翻译: {test_sentence} -> {translated_sentence}")
